name: frog_api

packages:
  - packages/**

scripts:
  build:
    run: >-
      dart pub global run melos exec --depends-on=build_runner
      dart run build_runner build
    description: Run build_runner in build mode

  build:watch:
    run: >-
      dart pub global run melos exec --depends-on=build_runner
      dart run build_runner watch
    description: Run build_runner in watch mode

  pre-commit:init:
    run: >-
      bash -c "echo -e
      '#!/bin/sh\nexec dart pub global run melos run pre-commit:run'
      > .git/hooks/pre-commit && chmod a+x .git/hooks/pre-commit"
    description: Setup pre commit hooks

  pre-commit:run:
    run: >-
      dart pub global run melos exec
      dart run dart_pre_commit
    description: Run pre commit hooks in all projects
