name: shelf_api

packages:
  - packages/**

scripts:

  pre-commit:init: >-
    bash -c "echo -e
    '#!/bin/sh\nexec dart pub global run melos run pre-commit:run'
    > .git/hooks/pre-commit && chmod a+x .git/hooks/pre-commit"

  pre-commit:run: >-
    dart pub global run melos exec --depends-on=dart_pre_commit
    dart run dart_pre_commit
