name: shelf_api_builder_example
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  dio: 
  shelf:
  shelf_api:
  shelf_router:

dev_dependencies:
  build_runner:
  shelf_api_builder:
    path: ..

dart_pre_commit:
  flutter-compat: false
