name: frog_api
description: A code generation based API package to make dart_frog even more awesome.
version: 1.0.0
homepage: https://github.com/Skycoder42/frog_api

environment:
  sdk: ^3.3.0

dependencies:
  dart_frog: ^1.1.0
  meta: ^1.11.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.10.1
  riverpod_generator: ^2.4.0
  test: ^1.25.4

cider:
  link_template:
    tag: https://github.com/Skycoder42/frog_api/releases/tag/frog_api-v%tag%
    diff: https://github.com/Skycoder42/frog_api/compare/frog_api-v%from%...frog_api-v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - meta
