name: shelf_api_example
publish_to: none

environment:
  sdk: ^3.3.0

platforms:
  linux:
  macos:
  windows:

dependencies:
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shelf: ^1.4.1
  shelf_api:
    path: ..
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

dart_pre_commit:
  flutter-compat: false
