name: shelf_api_example
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  riverpod: 
  riverpod_annotation: 
  shelf:
  shelf_api:
    path: ..
  shelf_router:

dev_dependencies:
  build_runner: 
  riverpod_generator: 
