name: frog_api_generator
description: The code generator for the frog_api package. Check it out for more details.
version: 1.0.0
homepage: https://github.com/Skycoder42/frog_api

environment:
  sdk: ^3.3.0

platforms:
  linux:
  macos:
  windows:

dependencies:
  frog_api: ^1.0.0

dev_dependencies:
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.10.1
  test: ^1.25.4

cider:
  link_template:
    tag: https://github.com/Skycoder42/frog_api/releases/tag/frog_api_generator-v%tag%
    diff: https://github.com/Skycoder42/frog_api/compare/frog_api_generator-v%from%...frog_api_generator-v%to%

dart_pre_commit:
  flutter-compat: false # TODO enable again after release
