builders:
  shelf_api_builder:
    import: "package:shelf_api_builder/shelf_api_builder.dart"
    builder_factories:
      - shelfApiBuilder
      - shelfApiClientBuilder
    build_extensions:
      ".dart":
        - ".api.dart"
        - ".client.dart"
    auto_apply: dependents
    build_to: source
    runs_before: ["retrofit_generator|retrofit_generator"]
