builders:
  shelf_api_builder:
    import: "package:shelf_api_builder/shelf_api_builder.dart"
    builder_factories:
      - shelfApiBuilder
      - shelfApiClientBuilder
    build_extensions:
      ".dart":
        - ".api.dart"
        - ".client.dart"
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        generateApi: true
        generateClient: true

targets:
  $default:
    builders:
      shelf_api_builder:
        enabled: true
        generate_for:
          include:
            - example/**
