builders:
  frog_api_builder:
    import: "package:frog_api_builder/frog_api_builder.dart"
    builder_factories: ["frogApiBuilder"]
    build_extensions: { ".dart": [".api.dart"] }
    auto_apply: dependents
    build_to: source
    # runs_before: ["retrofit|retrofit_generator"]
    defaults:
      generate_for: ["routes/**"]
