name: CI/CD for shelf_api

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "packages/shelf_api/**"
      - ".github/workflows/shelf_api_ci.yaml"
      - ".github/workflows/shelf_api_cd.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/shelf_api
      buildRunner: true
      unitTestPaths: -P unit
      coverageExclude: >-
        "**/*.g.dart"
      integrationTestPaths: -P integration

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/shelf_api
      tagPrefix: shelf_api-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
