name: CD - Publish shelf_api_builder to pub.dev

on:
  push:
    tags:
      - "shelf_api_builder-v*"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/shelf_api_builder
      buildRunner: true
      unitTestPaths: ""
      integrationTestPaths: -P integration

  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    needs:
      - ci
    permissions:
      id-token: write
    with:
      tagPrefix: shelf_api_builder-v
      workingDirectory: packages/shelf_api_builder
      buildRunner: true
